/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'apple' at '9/17/16 8:09 PM' with Gradle 2.14
 *
 * @author apple, @date 9/17/16 8:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
